name: Backend Test Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Simulated Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install --verbose

      - name: Verify Dependencies
        run: ls -la node_modules

      - name: Run Simulated Tests
        run: npm run test -- --coverage

      - name: Debug Files
        run: ls -la

  notify-success:
    name: Notify Success
    runs-on: ubuntu-20.04
    needs: test
    if: success()
    steps:
      - name: Notify Success
        run: |
          echo "✅ las pruebas pasaron con exito!"
          echo "El utimo comit lo hizo: ${{ github.actor }}"

  notify-failure:
    name: Notify Failure
    runs-on: ubuntu-20.04
    needs: test
    if: failure()
    steps:
      - name: Notify Failure
        run: |
          echo "❌ Las pruebas fallaraon!"
          echo "El utimo comit lo hizo: ${{ github.actor }}"

  notify-changes:
    name: Notify Changes
    runs-on: ubuntu-20.04
    steps:
      - name: Notify Changes
        run: |
          echo "🔔 un pull o push activo el pipeline"
          echo "Changes made by: ${{ github.actor }}"
