name: Backend Test Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install --verbose

      - name: Verify Dependencies
        run: ls -la node_modules

      - name: Run Simulated Tests
        run: npm run test -- --coverage

      - name: Debug Files
        run: ls -la

  security-audit:
    name: Security Audit
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run Security Audit
        run: npm audit --audit-level=moderate || echo "⚠️ los Audit se completaron con avisos!"

  notify-success:
    name: Notify Success
    runs-on: ubuntu-20.04
    needs: [test, security-audit]
    if: success()
    steps:
      - name: Notify Success
        run: |
          echo "✅ ¡Las pruebas y auditoría pasaron con éxito!"
          echo "El último commit lo hizo: ${{ github.actor }}"

  notify-failure:
    name: Notify Failure
    runs-on: ubuntu-20.04
    needs: [test, security-audit]
    if: failure()
    steps:
      - name: Notify Failure
        run: |
          echo "❌ Las pruebas o la auditoría fallaron."
          echo "El último commit lo hizo: ${{ github.actor }}"

  notify-changes:
    name: Notify Changes
    runs-on: ubuntu-20.04
    steps:
      - name: Notify Changes
        run: |
          echo "🔔 Un pull o push activó el pipeline."
          echo "Cambios hechos por: ${{ github.actor }}"
