name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Debug Files
        run: ls -la

      - name: Verify Dependencies
        run: ls -la node_modules

      - name: Run Unit Tests
        run: npm run test -- --coverage

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Environment
        run: echo "Deploying backend..."

      - name: Deploy Backend
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "Deploying to production"
            npm run start:prod 
          else
            echo "Deploying to staging"
            npm run start:dev
          fi

  notify:
    name: Send Notifications
    runs-on: ubuntu-20.04
    needs: deploy
    steps:
      - name: Notify Success
        if: always()
        run: |
          echo "Pipeline completed successfully!"

      - name: Notify Last Commit Author
        if: always()
        run: |
          echo "Pipeline triggered by: ${{ github.actor }}"

      - name: Notify Failure
        if: failure()
        run: |
          echo "Pipeline failed!"
